[package]
name = "file-encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
rand = "0.8"
generic-array = "0.14"
base64 = "0.13"
dotenv = "0.15.0"